[package]
name = "boon"
version = "0.6.1"
edition = "2021"
description = "JSONSchema (draft 2020-12, draft 2019-09, draft-7, draft-6, draft-4) Validation"
readme = "README.md"
repository = "https://github.com/xazukx/jsonschema"
authors = ["santhosh kumar tekuri <santhosh.tekuri@gmail.com>"]
keywords = ["jsonschema", "validation"]
license = "MIT OR Apache-2.0"
categories = ["web-programming"]
exclude = [ "tests", ".github", ".gitmodules" ]

[dependencies]
serde = "1"
serde_json = "1"
regex = "1.10.3"
regex-syntax = "0.8.2"
url = "2"
fluent-uri = "0.3.2"
idna = "1.0"
percent-encoding = "2"
once_cell = "1"
base64 = "0.22"
ahash = "0.8.3"
appendlist = "1.4"
jsonway = "2.0.0"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
ureq = "2.12"
rustls = "0.23"
criterion = "0.5"

[[bench]]
name = "bench"
harness = false
